# Generated by Django 5.1.1 on 2024-09-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_business_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='business_impact',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
    ]
