# Generated by Django 4.2.16 on 2024-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_business_impact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('task_type', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=100)),
                ('business_impact', models.CharField(max_length=100)),
                ('estimated_effort', models.FloatField()),
                ('priority_level', models.CharField(max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
